In [16]:
import sqlite3
import pandas as pd

# データベース接続
db_path = '/Users/muna/Hana_research/data/db/Hana_Research.db'
conn = sqlite3.connect(db_path)

# サムスカ導入が記載されている患者を抽出
query = """
SELECT *
FROM Background_summary
WHERE memo LIKE '%サムスカ導入%'
"""

df = pd.read_sql_query(query, conn)
conn.close()

# 結果表示
print(f"該当患者数: {len(df)}件")
df

該当患者数: 189件

,Patient_ID,PS,visit_place,facility,JABC,ninchido,Kaiyodo,memo,tag,Study_ID
0,190192,Grade 3,居宅,自宅,A2,Ⅲa,要介護3,\n・サムスカ導入(2021/1/31)\n・難病医療証あり！前月と当月ページ写真撮影(訪...,難病 訪看（医療保険）,P001408
1,220003,Grade 3,居宅,自宅,A1,Ⅲa,要介護1,\n・サムスカ導入(2024/12/13)\n・玄関について（正面と自宅裏にあり。2か所と...,マル障 ★マイナ,P003136
2,210163,Grade 4,居宅,自宅,B2,Ⅰ,要介護4,サムスカ導入(2022/1/20)\n※※フェントステープ処方時注意してください※※\n・フ...,在宅酸素 難病,P002606
3,240181,Grade 4,居宅,自宅,C1,Ⅲb,要介護5,・サムスカ導入(2026/4/1)\n・1回目 物品持参 備考参照 \n・2回目 尿カテ交換...,在宅酸素 PEG 尿道カテーテル 中心静脈 マル障 区分２,P004521
4,230392,Grade 2,居宅,自宅,A1,Ⅱb,要介護5,サムスカ導入(2024/5/17)\n・マンション敷地内に駐車時はボンネットに部屋番号用紙を...,NaN,P004099
...,...,...,...,...,...,...,...,...,...,...
184,210273,Grade 2,居宅,自宅,J2,Ⅱb,要介護2,サムスカ導入(2022/5/26)\n・COVID-19（ファイザー社製）２０２２年３月３日...,NaN,P002701
185,240052,Grade 3,居宅,自宅,B1,Ⅱa,要介護2,サムスカ導入(2024/5/1)\n・旧漢字のため保険証確認\n☆キーボックスあり、自宅の入...,PM 同一患家 マル障,P004407
186,210022,NaN,居宅,自宅,A2,Ⅱb,要介護4,サムスカ導入(2021/5/19)\n・COVID19④ファイザー22.8.10\n※H注意...,在宅酸素,P002486
187,170222,Grade 4,居宅,自宅,A2,Ⅱb,要介護1,サムスカ導入(2018/12/4)\n・予定を火曜以外にする場合は、前月中頃までに次女に連絡...,在宅酸素,P000717
188,210376,NaN,施設,学研ココファン日吉,A2,Ⅲa,要介護3,サムスカ導入(2023/4/23) \n*同姓同名患者有*\n・A221号\n・COVID-...,在宅酸素,P002792

In [17]:
import sqlite3
import pandas as pd

db_path = '/Users/muna/Hana_research/data/db/Hana_Research.db'
conn = sqlite3.connect(db_path)

# サムスカ導入 かつ 心疾患の患者を抽出
query = """
SELECT bs.*
FROM Background_summary bs
INNER JOIN first_diag fd ON bs.patient_id = fd.patient_id
WHERE bs.memo LIKE '%サムスカ導入%'
  AND fd.category = '【心疾患】'
"""

df = pd.read_sql_query(query, conn)
conn.close()

print(f"該当患者数: {len(df)}件")
df

該当患者数: 312件

,Patient_ID,PS,visit_place,facility,JABC,ninchido,Kaiyodo,memo,tag,Study_ID
0,190192,Grade 3,居宅,自宅,A2,Ⅲa,要介護3,\n・サムスカ導入(2021/1/31)\n・難病医療証あり！前月と当月ページ写真撮影(訪...,難病 訪看（医療保険）,P001408
1,190192,Grade 3,居宅,自宅,A2,Ⅲa,要介護3,\n・サムスカ導入(2021/1/31)\n・難病医療証あり！前月と当月ページ写真撮影(訪...,難病 訪看（医療保険）,P001408
2,220003,Grade 3,居宅,自宅,A1,Ⅲa,要介護1,\n・サムスカ導入(2024/12/13)\n・玄関について（正面と自宅裏にあり。2か所と...,マル障 ★マイナ,P003136
3,220003,Grade 3,居宅,自宅,A1,Ⅲa,要介護1,\n・サムスカ導入(2024/12/13)\n・玄関について（正面と自宅裏にあり。2か所と...,マル障 ★マイナ,P003136
4,210163,Grade 4,居宅,自宅,B2,Ⅰ,要介護4,サムスカ導入(2022/1/20)\n※※フェントステープ処方時注意してください※※\n・フ...,在宅酸素 難病,P002606
...,...,...,...,...,...,...,...,...,...,...
307,210022,NaN,居宅,自宅,A2,Ⅱb,要介護4,サムスカ導入(2021/5/19)\n・COVID19④ファイザー22.8.10\n※H注意...,在宅酸素,P002486
308,170222,Grade 4,居宅,自宅,A2,Ⅱb,要介護1,サムスカ導入(2018/12/4)\n・予定を火曜以外にする場合は、前月中頃までに次女に連絡...,在宅酸素,P000717
309,170222,Grade 4,居宅,自宅,A2,Ⅱb,要介護1,サムスカ導入(2018/12/4)\n・予定を火曜以外にする場合は、前月中頃までに次女に連絡...,在宅酸素,P000717
310,210376,NaN,施設,学研ココファン日吉,A2,Ⅲa,要介護3,サムスカ導入(2023/4/23) \n*同姓同名患者有*\n・A221号\n・COVID-...,在宅酸素,P002792
311,210376,NaN,施設,学研ココファン日吉,A2,Ⅲa,要介護3,サムスカ導入(2023/4/23) \n*同姓同名患者有*\n・A221号\n・COVID-...,在宅酸素,P002792

In [18]:
conn = sqlite3.connect(db_path)

# first_diagで心疾患の患者ごとの行数を確認
check = pd.read_sql_query("""
    SELECT patient_id, COUNT(*) as count
    FROM first_diag
    WHERE category = '【心疾患】'
    GROUP BY patient_id
    HAVING COUNT(*) > 1
""", conn)

print(f"複数行ある患者: {len(check)}件")
print(check)
conn.close()

複数行ある患者: 857件
     Patient_ID  count
0        150002      2
1        150003      3
2        150004      3
3        150006      2
4        150007      3
..          ...    ...
852      241376      2
853      241377      2
854      250001      3
855      250024      2
856      250036      3

[857 rows x 2 columns]

In [19]:
conn = sqlite3.connect(db_path)

query = """
SELECT DISTINCT bs.*
FROM Background_summary bs
INNER JOIN first_diag fd ON bs.patient_id = fd.patient_id
WHERE bs.memo LIKE '%サムスカ導入%'
  AND fd.category = '【心疾患】'
"""

df = pd.read_sql_query(query, conn)
conn.close()

print(f"該当患者数: {len(df)}件")
df

該当患者数: 139件

,Patient_ID,PS,visit_place,facility,JABC,ninchido,Kaiyodo,memo,tag,Study_ID
0,190192,Grade 3,居宅,自宅,A2,Ⅲa,要介護3,\n・サムスカ導入(2021/1/31)\n・難病医療証あり！前月と当月ページ写真撮影(訪...,難病 訪看（医療保険）,P001408
1,220003,Grade 3,居宅,自宅,A1,Ⅲa,要介護1,\n・サムスカ導入(2024/12/13)\n・玄関について（正面と自宅裏にあり。2か所と...,マル障 ★マイナ,P003136
2,210163,Grade 4,居宅,自宅,B2,Ⅰ,要介護4,サムスカ導入(2022/1/20)\n※※フェントステープ処方時注意してください※※\n・フ...,在宅酸素 難病,P002606
3,240181,Grade 4,居宅,自宅,C1,Ⅲb,要介護5,・サムスカ導入(2026/4/1)\n・1回目 物品持参 備考参照 \n・2回目 尿カテ交換...,在宅酸素 PEG 尿道カテーテル 中心静脈 マル障 区分２,P004521
4,230392,Grade 2,居宅,自宅,A1,Ⅱb,要介護5,サムスカ導入(2024/5/17)\n・マンション敷地内に駐車時はボンネットに部屋番号用紙を...,NaN,P004099
...,...,...,...,...,...,...,...,...,...,...
134,210273,Grade 2,居宅,自宅,J2,Ⅱb,要介護2,サムスカ導入(2022/5/26)\n・COVID-19（ファイザー社製）２０２２年３月３日...,NaN,P002701
135,240052,Grade 3,居宅,自宅,B1,Ⅱa,要介護2,サムスカ導入(2024/5/1)\n・旧漢字のため保険証確認\n☆キーボックスあり、自宅の入...,PM 同一患家 マル障,P004407
136,210022,NaN,居宅,自宅,A2,Ⅱb,要介護4,サムスカ導入(2021/5/19)\n・COVID19④ファイザー22.8.10\n※H注意...,在宅酸素,P002486
137,170222,Grade 4,居宅,自宅,A2,Ⅱb,要介護1,サムスカ導入(2018/12/4)\n・予定を火曜以外にする場合は、前月中頃までに次女に連絡...,在宅酸素,P000717
138,210376,NaN,施設,学研ココファン日吉,A2,Ⅲa,要介護3,サムスカ導入(2023/4/23) \n*同姓同名患者有*\n・A221号\n・COVID-...,在宅酸素,P002792

In [20]:
# CSVファイルとして保存
output_path = '/Users/muna/Desktop/サムスカ導入_心疾患.csv'
df.to_csv(output_path, index=False, encoding='utf_8_sig')

print(f"保存完了: {output_path}")
print(f"件数: {len(df)}件")

保存完了: /Users/muna/Desktop/サムスカ導入_心疾患.csv
件数: 139件

In [21]:
import sqlite3
import pandas as pd
import re

db_path = '/Users/muna/Hana_research/data/db/Hana_Research.db'
conn = sqlite3.connect(db_path)

df = pd.read_sql("SELECT Patient_ID, memo FROM Background_summary WHERE memo LIKE '%サムスカ導入%'", conn)
conn.close()

# 日付が抽出できなかった行を表示
def extract_date(memo):
    match = re.search(r'サムスカ導入\((\d{4})/(\d{1,2})/(\d{1,2})\)', memo)
    return match is not None

df["extracted"] = df["memo"].apply(extract_date)
no_match = df[~df["extracted"]]

print(f"日付抽出できなかった件数: {len(no_match)}")
for _, row in no_match.iterrows():
    # サムスカ導入前後30文字だけ表示
    idx = row["memo"].find("サムスカ導入")
    print(f"\nPatient_ID: {row['Patient_ID']}")
    print(row["memo"][max(0, idx-5):idx+30])

日付抽出できなかった件数: 4

Patient_ID: 230169
サムスカ導入(2023/6)
・医療的連絡は次女に、時間連絡

Patient_ID: 220194
サムスカ導入(2022/6)
6月28日感謝済。
・COVI

Patient_ID: 160097
サムスカ導入2023/11/21
・414号室
・居室入って

Patient_ID: 150067
サムスカ導入(2015/7)
# 慢性心不全（preserv

In [1]:
import pandas as pd
import sqlite3

db_path = "/Users/muna/Hana_research/data/db/Hana_Research.db"

conn = sqlite3.connect(db_path)

df = pd.read_sql_query(
    "SELECT * FROM tolvaptan_study",
    conn
)

output_path = "/Users/muna/Hana_research/data/processed/tolvaptan_study.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("export completed")

export completed